import type { Metadata } from "next";
import { MedievalSharp, EB_Garamond } from "next/font/google";
import "./globals.css";

const medieval = MedievalSharp({
  weight: "400",
  variable: "--font-medieval",
  subsets: ["latin", "latin-ext"],
});

const garamond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="cs"
      suppressHydrationWarning
      className={`${medieval.variable} ${garamond.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-garamond bg-[#1a120b] text-[#f4ecd8]">{children}</body>
    </html>
  );
}
